name: km_csf
description: Carnet de trajets
publish_to: "none"
version: 1.0.7+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  share_plus: ^10.0.0
  path_provider: ^2.1.4
  excel: ^4.0.6
  shared_preferences: ^2.3.2
  file_picker: ^8.0.0 # <--- Vérifie que cette ligne est présente
  permission_handler: ^12.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon_trajets.png