name: km_csf
description: Carnet de trajets
publish_to: "none"
version: 1.0.7+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  excel: ^4.0.6
  shared_preferences: ^2.5.4
  file_picker: ^10.3.10 # <--- Vérifie que cette ligne est présente
  permission_handler: ^12.0.1
  pdf: ^3.11.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon_trajets.png