name: km_csf
description: Carnet de trajets
publish_to: "none"
version: 1.0.4+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  share_plus: ^10.0.0
  path_provider: ^2.1.4
  excel: ^4.0.6
  shared_preferences: ^2.3.2
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon_trajets.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_trajets.png"
