name: carnet_trajets
description: Suivi des dÃ©placements et kilomÃ¨tres.
publish_to: 'none'

environment:
  sdk: '^3.2.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  share_plus: ^7.2.2
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  excel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon_trajets.png
